baseURL = '/'
locale = 'zh-cn'
title = 'library-A4'
theme = 'PaperMod'

buildFuture = true

disablePathToLower = true

[params]
  ShowSearch = true
  fuseOpts = { isCaseSensitive = false, minMatchCharLength = 2, shouldSort = true }
  description = '千页成书，万言叙事。'
  ShowReadingTime = true
  ShowShareButtons = true
  ShowBreadCrumbs = true

[params.homeInfoParams]
  Title = "library-a4 加载完毕"
  Content = "欢迎回来,■■"

[[menu.main]]
  name = "分类"
  url = "/categories/"
  weight = 10

[[menu.main]]
  name = "标签"
  url = "/tags/"
  weight = 20

[[menu.main]]
  name = "归档"
  url = "/posts/"
  weight = 30

[outputs]
  home = ["HTML", "RSS", "JSON"]

[server]
  [[server.headers]]
    for = "/css/*.css"
    [server.headers.values]
      Content-Type = "text/css; charset=utf-8"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true   # 允许文章中嵌入安全 HTML