baseURL = '/'
locale = 'zh-cn'
title = 'library-A4'
theme = 'PaperMod'

buildFuture = true

[params]
  description = '千页成书，万言叙事。'
  ShowReadingTime = true
  ShowShareButtons = true
  ShowBreadCrumbs = true

[params.homeInfoParams]
  Title = "library-a4 加载完毕"
  Content = "欢迎回来,■■"

[module]
  [[module.mounts]]
    source = "content"
    target = "content"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "data"
    target = "data"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "i18n"
    target = "i18n"
  [[module.mounts]]
    source = "archetypes"
    target = "archetypes"

[[menu.main]]
  name = "分类"
  url = "/categories/"
  weight = 10

[[menu.main]]
  name = "标签"
  url = "/tags/"
  weight = 20

[[menu.main]]
  name = "归档"
  url = "/posts/"
  weight = 30